project_id = "mhcyyjxiwpteonviujso"

[functions.marketplace-checkout]
verify_jwt = true

[functions.marketplace-payment-webhook]
verify_jwt = false

[functions.marketplace-payment-return]
verify_jwt = false
